apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front
  labels:
    app: {{ .Release.Name }}-front
spec:
  ports:
  - port: {{ .Values.front.port }}
    targetPort: {{ .Values.front.targetport }}
    name: {{ .Release.Name }}-front
  selector:
    app: {{ .Release.Name }}-front